### ISSUE TITLE
Windows: site-packages marked as "editable package"

### ISSUE THREAD

**Issue by qubey** [conda/conda-pack#66]
I created a new environment to test this out on my Windows machine, and for some reason it's saying that `site-packages` is an editable package which is preventing me from using conda-pack:

```
(my_env) C:\Users\me>conda pack --zip-symlinks --format zip
Collecting packages...
CondaPackError: Cannot pack an environment with editable packages
installed (e.g. from `python setup.py develop` or
 `pip install -e`). Editable packages found:

- c:\users\me\appdata\local\conda\conda\envs\my_env\lib\site-packages
```

**Comment by jcrist** [comment]
Did you install something using `pip install -e .` or `python setup.py develop`? Can you provide a reproducible example?

**Comment by qubey** [comment]
I actually never did... I only installed something using `pip install .`, no `-e` flag

Let me see if I can work through the simplest repro for this.  I did notice that matplotlib had a .pth file that didn't start with `#`, as this line checks: https://github.com/conda/conda-pack/blob/master/conda_pack/core.py#L499

Let me see what I can put together

**Comment by yogeshhk** [comment]
I am facing the same issue. I did not install any package with "pip install -e" but plain "pip install".
I am trying to zip default Miniconda3 environment, to be taken to a pen-drive. Please suggest any steps to resolve this issue.

**Comment by jcrist** [comment]
Should be fixed by #83.

**Comment by Phillip-M-Feldman** [comment]
I'm still seeing this issue (as of two days ago): CondaPackError: Cannot pack an environment with editable packages installed (e.g. from `python setup.py develop` or `pip install -e`). Editable packages found:
- /opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages
